// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBem4KZ15giD-q1Ts2VbK3XC8PNF0iUjKI',
    appId: '1:968028326066:web:3e6af463683c729d5c61ab',
    messagingSenderId: '968028326066',
    projectId: 'loginapi-d9278',
    authDomain: 'loginapi-d9278.firebaseapp.com',
    storageBucket: 'loginapi-d9278.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYVbA66Z9Uynq-pU3Sx_E6YV7AazNxKU',
    appId: '1:968028326066:android:ed9e0ac2719ce1b55c61ab',
    messagingSenderId: '968028326066',
    projectId: 'loginapi-d9278',
    storageBucket: 'loginapi-d9278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8wuPeYGJ_JBaR13BxKTc4fe0CbZ4iYc',
    appId: '1:968028326066:ios:1b6eb6901aa071905c61ab',
    messagingSenderId: '968028326066',
    projectId: 'loginapi-d9278',
    storageBucket: 'loginapi-d9278.firebasestorage.app',
    iosBundleId: 'com.example.portfoliowithapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC8wuPeYGJ_JBaR13BxKTc4fe0CbZ4iYc',
    appId: '1:968028326066:ios:1b6eb6901aa071905c61ab',
    messagingSenderId: '968028326066',
    projectId: 'loginapi-d9278',
    storageBucket: 'loginapi-d9278.firebasestorage.app',
    iosBundleId: 'com.example.portfoliowithapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBem4KZ15giD-q1Ts2VbK3XC8PNF0iUjKI',
    appId: '1:968028326066:web:5b0941bf0cfc1d0a5c61ab',
    messagingSenderId: '968028326066',
    projectId: 'loginapi-d9278',
    authDomain: 'loginapi-d9278.firebaseapp.com',
    storageBucket: 'loginapi-d9278.firebasestorage.app',
  );
}
